"""empty message

Revision ID: b4f4333b8b3c
Revises: 47d6c8961a5d
Create Date: 2023-04-23 19:35:42.936899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f4333b8b3c'
down_revision = '47d6c8961a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('booking_service_workers_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'services_workers', ['service_workers_id'], ['id'])

    with op.batch_alter_table('services_workers', schema=None) as batch_op:
        batch_op.drop_constraint('services_workers_booking_id_fkey', type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('services_workers_booking_id_fkey', 'booking', ['booking_id'], ['id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('booking_service_workers_id_fkey', 'services', ['service_workers_id'], ['id'])

    # ### end Alembic commands ###
